### ISSUE TITLE
I could not run this package with ResolutionError

### ISSUE THREAD

**Issue by doyeon94** [ghoresh11/sling#5]
Hello,

I had a problem to run sling.
After installing the requirements and your package, I tried to run sling.
However, I faced this error, and could overcome it yet. 
Is it because I am using python3? or how can I fix it?

(base) [doyeon@sbvas sling]$ sling run test_ID /home/doyeon/coPROJECT/imb/sequence_operon/data
Traceback (most recent call last):
  File "/opt/user/doyeon/anaconda3/bin/sling", line 4, in <module>
    __import__('pkg_resources').run_script('sling==2.0.1', 'sling')
  File "/opt/user/doyeon/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/user/doyeon/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1451, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/sling' not found in metadata at '/opt/user/doyeon/anaconda3/lib/python3.8/site-packages/sling-2.0.1.dist-info'

Thanks

**Comment by ghoresh11** [comment]
Hi, please use python 2.7.
